### ISSUE TITLE
does this trigger "later in life"?

### ISSUE THREAD

**Issue by krtschmr** [Khan/pull-request-comment-trigger#15]
we have a PR and when the tester comments "start_testing!" we want to spin up a test environment for this branch.
i had the idea that we _just need to listen_ for comments in PRs and your action would be sufficient, but nothing here gets triggered. 

am i right with the assumption, that our usecase won't work?

```
name: Starting a test environment
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  spinup:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'start_testing!'
      - run: 'sh deploy.sh #here we can run the pipeline to spin up an environment'
        if: steps.check.outputs.triggered == 'true'


```

**Comment by BhumikaSaini** [comment]
Hi @krtschmr,
I believe you missed passing the `GITHUB_TOKEN`. Please can you try updating your step as per below:
```
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'start_testing!'
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
```
