### ISSUE TITLE
Prefix_only doesn't work

### ISSUE THREAD

**Issue by GabrieleCalarota** [Khan/pull-request-comment-trigger#18]
Hi,

I'm encountering this issue using this action khan/pull-request-comment-trigger@master using:

```
        - uses: khan/pull-request-comment-trigger@master
          id: check
          with:
            trigger: '!deploy'
            prefix_only: 'true'
            reaction: rocket
          env:
            GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
```

Action gets triggered also if "!deploy" is in the middle of a comment (not according to README.md docs)

Also --> trying to get steps.check.outputs.comment_body is empty
