### ISSUE TITLE
what's so special about "check"?

### ISSUE THREAD

**Issue by martinburch** [Khan/pull-request-comment-trigger#27]
I thought since the `id` was `check`, changing the `id` to, say, `lint`, would allow changing

if: steps.**check**.outputs.triggered == 'true'
to
if: steps.**lint**.outputs.triggered == 'true'

however, this didn't work, steps.**lint**.outputs.triggered == 'true' never cause the next step to run

```
      - uses: khan/pull-request-comment-trigger@master
         id: lint
         with:
           trigger: '/lint'
           reaction: rocket
         env:
           GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
       - uses: yu-iskw/action-sqlfluff@v3
         if: steps.lint.outputs.triggered == 'true'
```

when I changed back to `check` everything worked as expected. Why is this? Doesn't really conform with the documentation here: https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context which says you may access `steps.<step_id>.outputs`
