### ISSUE TITLE
[suggest] trim comment

### ISSUE THREAD

**Issue by seunggabi** [Khan/pull-request-comment-trigger#29]
### `.github/workflows/preview.yml`
```
    - uses: bucketplace/comment-trigger@v1.0
      id: check
      with:
        trigger: '/preview'
        reaction: rocket
```

---

### it's works
```
/preview
```

### it's works
```

/preview 

```
