### ISSUE TITLE
`steps.check.outputs.comment_body` is blank

### ISSUE THREAD

**Issue by ianshmean** [Khan/pull-request-comment-trigger#6]
`steps.check.outputs.comment_body` seems to always be blank for me. 

```
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'RunTest'
          prefix_only: 'true'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: 'echo ${{ steps.check.outputs.comment_body }}'
        if: steps.check.outputs.triggered == 'true'
```

I'm triggering this with a comment `RunTest test1` hoping that the job runs `echo RunTest test1`

However I get `echo ` as the step name and a blank echo output.

If I replace the echo with 'echo ${{ steps.check.outputs.trigger }}' I get `echo true` so it seems `comment_body` has an issue

**Comment by ianshmean** [comment]
A workaround is to use `github.event.comment.body`
```
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'RunTest'
          prefix_only: 'true'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - run: echo '${{ github.event.comment.body }}'
        if: steps.check.outputs.triggered == 'true'
```
