### ISSUE TITLE
Does this action still work?

### ISSUE THREAD

**Issue by heathsnow** [Khan/pull-request-comment-trigger#7]
No matter what I do I can't get this action to execute with a PR comment.  My workflow is:
```
name: 'deploypr'
on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  deploypr:
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: 'deploy'
          prefix_only: 'true'
          reaction: rocket
        env:
          GITHUB_TOKEN: `${{ secrets.GITHUB_TOKEN }}`
      - run: 'echo Found it!'
        if: steps.check.outputs.triggered == 'true'
```
However when I type a comment with only the word `deploy` there is no action executed.  Am I missing something?
